### ISSUE TITLE
US 10 - As a homeowner, I want to edit my user profile so that I can manage my personal information and preferences within the application.

### ISSUE THREAD

**Issue by huiyinghuan** [huiyinghuan/team12_PSD_NILM_Mobile_Application#21]

**Comment by huiyinghuan** [comment]
it should be US 10 - As a homeowner, I want to edit my user profile so that I can manage my personal information and preferences within the application. 

please make the necessary changes @NotAnima

**Comment by NotAnima** [comment]
Changed the User story, sorry for the wrong description and thanks for pointing it out! @huiyinghuan
